### ISSUE TITLE
Upload files as HTML

### ISSUE THREAD

**Issue by dimoschi** [transifex/transifex-sync-zendesk#51] opened 2015-11-11 07:54 UTC
As we talked already with @matthewjackowski, if we upload the files as HTML files, we could take advantage of the HTML view in Web Editor. Then, it would be possible for translators to work on strings, containing HTML tags.

**Comment by diegobz** [comment] 2016-06-07 05:53
Duplicate of #21

**Closed by diegobz** 2016-06-07 05:53 UTC
